BOX_IMAGE = "ubuntu/focal64"
NODE_COUNT = 3


Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "ubuntu#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "ubuntu#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu#{i}"
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  end
end